apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dragos1993/app1-openshift-argocd.git
    targetRevision: main
    path: k8s/helm
    helm:
      releaseName: app1
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: app1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
