apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app1-helm-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: app1-postgres
            appName: postgres
            path: apps/app-postgres/posgres
          - name: app1-backend
            appName: backend
            path: apps/app-backend/bakend
          - name: app1-frontend
            appName: frontend
            path: apps/app-frontend/frontend
  template:
    metadata:
      name: "{{ element.name }}"
    spec:
      project: default
      source:
        repoURL: https://github.com/dragos1993/app1-openshift-argocd.git
        targetRevision: main
        path: k8s/helm
        helm:
          releaseName: "{{ element.appName }}"
          valueFiles:
            - "{{ element.path }}/values.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: app1
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
