apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app1-helm-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/dragos1993/app1-openshift-argocd.git
        revision: main
        directories:
          - path: k8s/helm
  template:
    metadata:
      name: app1-helm
    spec:
      project: default
      source:
        repoURL: https://github.com/dragos1993/app1-openshift-argocd.git
        targetRevision: main
        path: k8s/helm
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: app1
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
