apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: {{ .Values.namespace }}
data:
  DB_USER: {{ .Values.config.dbUser | quote }}
  DB_NAME: {{ .Values.config.dbName | quote }}
  DB_HOST: {{ .Values.config.dbHost | quote }}
  DB_PORT: {{ .Values.config.dbPort | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-user-config
  namespace: {{ .Values.namespace }}
data:
  ADMIN_USER: {{ .Values.config.adminUser | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secret.dbPassword | quote }}
  JWT_SECRET: {{ .Values.secret.jwtSecret | quote }}
